repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.5
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
